trigger:
- master

pool:
  vmImage: 'macOS-10.15'

variables:
  scheme: ''
  sdk: 'macosx10.15'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false

- script: ls -l $(agent.buildDirectory)
  displayName: 'listing output'
