trigger:
- master

pool:
  vmImage: 'macOS-10.15'

variables:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'

steps:
- script: echo "path/to/file"
# - script: codesign -d -vvvvvv /bin/ls
  # displayName: 'path/to/file'
