trigger:
- master

pool:
  vmImage: 'macOS-10.15'

variables:
  scheme: ''
  sdk: 'macosx10.15'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false

- script: ls -l $(agent.buildDirectory)/output/$(sdk)/$(configuration)
  displayName: 'listing output'

- script: ls -l $(agent.buildDirectory)/output/$(sdk)/$(configuration)\swiftpath
    displayName: 'Test Run'
